#!/bin/bash

fact()
{
	local number=$cn
	if [ "$cn" -eq 1 ]
	then 
		rez=1;
	else
		let cn=$cn-1;
		fact $cn;
		rez=$((rez*number))
	fi
return $rez;
}

if [ -z $1 ]
then
	read -p "n=" n
else
	n=$1
fi

if [ "$n" -lt 1 ]
then
	echo "Numarul trebuie sa fie mai mare sau egal cu 1"
	exit 1;
fi

cn=$n;
fact $cn;
echo "$n!=$rez"
